export const GET_ALL_POKEMONS = 'GET_ALL_POKEMONS'
export const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL'
export const GET_POKEMON_BY_NAME = 'GET_POKEMON_BY_NAME'
export const CREATE_POKEMON = 'CREATE_POKEMON'
export const CLEAR_PAGE = 'CLEAR_PAGE'
export const GET_ALL_TYPES = 'GET_ALL_TYPES'
export const SET_LOADING = "SET_LOADING"